dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.8.3
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3
  - Uniswap/uniswap-v3-periphery@1.3.0
  - Uniswap/v3-core@1.0.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.3'
      - '@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3'
      - '@uniswap=Uniswap/uniswap-v3-periphery@1.3.0'
      - '@uniswap-v3-core=Uniswap/v3-core@1.0.0'
dotenv: .env
networks:
  sepolia:
    verify: False
  mainnet-fork-dev:
    verify: False
  mumbai-fork-dev:
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
  polygon-test:
    verify: True
  Mumbai-Ankr:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}